export const eventStatuses = ["DRAFT", "PENDING_APPROVAL", "APPROVED", "REJECTED", "CANCELLED", "COMPLETED"] as const

export const eventCategories = [
  "conference",
  "workshop",
  "seminar",
  "concert",
  "festival",
  "sports",
  "networking",
  "fundraiser",
  "party",
  "exhibition",
  "meetup",
  "webinar",
  "class",
  "retreat",
  "other",
] as const

export const eventSearchableFields = [
  "title",
  "description",
  "shortDescription",
  "venueName",
  "city",
  "state",
  "country",
  "category",
]

export const eventFilterableFields = [
  "searchTerm",
  "status",
  "category",
  "isVirtual",
  "isPrivate",
  "city",
  "state",
  "country",
  "organizerId",
  "startDateFrom",
  "startDateTo",
  "minPrice",
  "maxPrice",
]

export const eventSelectFields = {
  id: true,
  title: true,
  slug: true,
  description: true,
  shortDescription: true,
  startDate: true,
  endDate: true,
  timezone: true,
  isVirtual: true,
  venueName: true,
  venueAddress: true,
  city: true,
  state: true,
  country: true,
  postalCode: true,
  latitude: true,
  longitude: true,
  virtualLink: true,
  virtualPlatform: true,
  coverImage: true,
  thumbnailImage: true,
  images: true,
  capacity: true,
  isPrivate: true,
  requiresApproval: true,
  ageRestriction: true,
  status: true,
  category: true,
  tags: true,
  metaTitle: true,
  metaDescription: true,
  organizerId: true,
  createdAt: true,
  updatedAt: true,
}

export const eventListSelectFields = {
  id: true,
  title: true,
  slug: true,
  shortDescription: true,
  startDate: true,
  endDate: true,
  isVirtual: true,
  venueName: true,
  city: true,
  state: true,
  country: true,
  coverImage: true,
  thumbnailImage: true,
  capacity: true,
  status: true,
  category: true,
  organizer: {
    select: {
      id: true,
      firstName: true,
      lastName: true,
      organizationName: true,
      avatar: true,
    },
  },
  _count: {
    select: {
      tickets: true,
      ticketTypes: true,
    },
  },
}
